Vagrant.configure("2")do|config|
  config.vm.box="b2.tp4-centos"

  # Ajoutez cette ligne afin d'accélérer le démarrage de la VM (si une erreur 'vbguest' est levée, voir la note un peu plus bas)
  config.vbguest.auto_update = false

  # Désactive les updates auto qui peuvent ralentir le lancement de la machine
  config.vm.box_check_update = false 

  # La ligne suivante permet de désactiver le montage d'un dossier partagé (ne marche pas tout le temps directement suivant vos OS, versions d'OS, etc.)
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "gitea" do |gitea|
    gitea.vm.network "public_network", ip:"192.168.1.11"
    gitea.vm.network "private_network", ip:"192.168.2.21"
    gitea.vm.hostname = "stack.gitea"
    gitea.vm.define "stack.gitea"
    gitea.vm.provision "shell", path: "script.sh"
    gitea.vm.provider :virtualbox do |vb|
      vb.memory = "1024"
    end
  end

  config.vm.define "mariadb" do |mariadb|
    mariadb.vm.network "public_network", ip:"192.168.1.12"
    mariadb.vm.network "private_network", ip:"192.168.2.22"
    mariadb.vm.hostname = "stack.mariadb"
    mariadb.vm.define "stack.mariadb"
    mariadb.vm.provision "shell", path: "script2.sh"
    mariadb.vm.provider :virtualbox do |vb|
      vb.memory = "1024"
    end
  end

  config.vm.define "nginx" do |nginx|
    nginx.vm.network "public_network", ip:"192.168.1.13"
    nginx.vm.network "private_network", ip:"192.168.2.23"
    nginx.vm.hostname = "stack.nginx"
    nginx.vm.define "stack.nginx"
    nginx.vm.provision "shell", path: "script3.sh"
    nginx.vm.provider :virtualbox do |vb|
      vb.memory = "1024"
    end
  end

  config.vm.define "nfs" do |nfs|
    nfs.vm.network "public_network", ip:"192.168.1.14"
    nfs.vm.network "private_network", ip:"192.168.2.24"
    nfs.vm.hostname = "stack.nfs"
    nfs.vm.define "stack.nfs"
    nfs.vm.provision "shell", path: "script4.sh"
    nfs.vm.provider :virtualbox do |vb|
      vb.memory = "1024"
    end
  end

  config.vm.define "save" do |save|
    save.vm.network "public_network", ip:"192.168.1.15"
    save.vm.network "private_network", ip:"192.168.2.25"
    save.vm.hostname = "stack.save"
    save.vm.define "stack.save"
    save.vm.provision "shell", path: "script5.sh"
    save.vm.provider :virtualbox do |vb|
      vb.memory = "1024"
    end
  end

end
