CONTROL_NODE_DISK1 = './tmp/large_disk1.vdi'

Vagrant.configure("2")do|config|
  config.vm.box="centos/7"

  # Ajoutez cette ligne afin d'accélérer le démarrage de la VM (si une erreur 'vbguest' est levée, voir la note un peu plus bas)
  config.vbguest.auto_update = false

  # Désactive les updates auto qui peuvent ralentir le lancement de la machine
  config.vm.box_check_update = false 

  # La ligne suivante permet de désactiver le montage d'un dossier partagé (ne marche pas tout le temps directement suivant vos OS, versions d'OS, etc.)
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "shell", path: "script2.sh"

  config.vm.define "tp4" do |tp4|
    tp4.vm.network "public_network", ip:"192.168.1.13", hostname: true
    tp4.vm.network "private_network", type: "dhcp"
    tp4.vm.hostname = "tp4.b2"
    tp4.vm.define "tp4"
    tp4.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      unless File.exist?(CONTROL_NODE_DISK1)
        vb.customize ['createhd', '--filename', CONTROL_NODE_DISK1, '--variant', 'Fixed', '--size', 5 * 1024]
      end
      vb.customize ['storageattach', :id,  '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', CONTROL_NODE_DISK1]
    end
  end

end
