Vagrant.configure("2")do|config|
  config.vm.box="centos/7"

  # Ajoutez cette ligne afin d'accélérer le démarrage de la VM (si une erreur 'vbguest' est levée, voir la note un peu plus bas)
  config.vbguest.auto_update = false

  # Désactive les updates auto qui peuvent ralentir le lancement de la machine
  config.vm.box_check_update = false 

  # La ligne suivante permet de désactiver le montage d'un dossier partagé (ne marche pas tout le temps directement suivant vos OS, versions d'OS, etc.)
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.network "public_network", ip:"192.168.2.11"

  config.vm.hostname = "tp2.vagrant"

  config.vm.define "TP2_Vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "TP2_Vagrant"
    vb.memory = "1024"
  end

end

CONTROL_NODE_DISK = './tmp/large_disk.vdi'

Vagrant.configure("2")do|config|
  config.vm.box="b2-tp2-centos"

  # Ajoutez cette ligne afin d'accélérer le démarrage de la VM (si une erreur 'vbguest' est levée, voir la note un peu plus bas)
  config.vbguest.auto_update = false

  # Désactive les updates auto qui peuvent ralentir le lancement de la machine
  config.vm.box_check_update = false 

  # La ligne suivante permet de désactiver le montage d'un dossier partagé (ne marche pas tout le temps directement suivant vos OS, versions d'OS, etc.)
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.network "public_network", ip:"192.168.2.11"

  config.vm.hostname = "tp2.vagrant"

  config.vm.define "TP2_Vagrant"
  
  config.vm.provision "shell", path: "script.sh"

  config.vm.disk :disk, name: "disk2", size: "5GB"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "TP2_Vagrant"
    vb.memory = "1024"
    unless File.exist?(CONTROL_NODE_DISK)
      vb.customize ['createhd', '--filename', CONTROL_NODE_DISK, '--variant', 'Fixed', '--size', 5 * 1024]
    end

    # Attache le disque à la VM
    vb.customize ['storageattach', :id,  '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', CONTROL_NODE_DISK]
  end

end
